### ISSUE TITLE
Container Access on Platform

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/roadmap#20] opened 2022-07-20 14:25 UTC
**Tell us about your request. If your feature request is related to a problem, please describe.**
I want to be able to open a shell into any of the containers in my uffizzi environment and run commands.

i.e. mount a rails console

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Select roadmap project --> in Settings for this issue**

**Comment by gadkins** [comment] 2022-07-27 18:48
Closing this issue as it is a duplicate of https://github.com/UffizziCloud/roadmap/issues/8

**Closed as completed by gadkins** 2022-07-27 18:48 UTC
